version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    user: root 
    restart: always
    ports:
      - '80:8080'
      - '50000:50000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime'
      - './data/jenkins_home:/var/jenkins_home'
      - './data/plug:/data/jenkins'

